GET http://localhost:3000/users
Accept: application/json

###

POST http://localhost:3000/users
Accept: application/json
Content-Type: application/json

{
  "name": "ТЕСТ",
  "about": "ТЕСТ",
  "avatar": "https://ic.pics.livejournal.com/bav_eot/44066703/942996/942996_original.jpg"
}
###
GET http://localhost:3000/users/638661c518c66c218a8bd02
Accept: application/json

###

POST http://localhost:3000/cards
Accept: application/json
Content-Type: application/json

{
  "name": "Тестqqqsasasasasasa11112" ,
  "link": "https://ic.pics.livejournal.com/bav_eot/44066703/942996/942996_original.jpg"
}


###
GET http://localhost:3000/cards
Accept: application/json

###

DELETE http://localhost:3000/cards/638c79085c4fddaa69902477
Accept: application/json

###

PUT http://localhost:3000/cards/638c79545c4fddaa69902479/likes
Accept: application/json

###

DELETE http://localhost:3000/cards/638c79545c4fddaa69902479/likes
Accept: application/json


####

PATCH http://localhost:3000/indiasasasdas/saasdds
Accept: application/json


####

PATCH http://localhost:3000/users/me
Accept: application/json
Content-Type: application/json

{
  "name": "a22",
  "about": "Минин"
}
###
